FROM rust:1.57.0

RUN mkdir -p /app

WORKDIR /app

RUN apt-get -y update && \
     apt-get -y upgrade  && \
     apt -y install libpq-dev

RUN cargo install cargo-watch
RUN cargo install diesel_cli --no-default-features --features postgres






# FROM rust:1.57.0

# WORKDIR /app

# RUN cargo install cargo-watch