version: "3.4"
services:
  postgres:
    image: postgres:alpine
    volumes:
      - pg_rocket:/var/lib/postgresql/data
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      PGPASSWORD: "docker"
    networks:
      - filter_net
    ports:
      - "5433:5432"

networks:
  filter_net:
    driver: bridge

volumes:
  pg_rocket:
    driver: local
