[debug]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"
limits = { forms = 32768 }

[release]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "critical"
limits = { forms = 32768 }