###
# @name newPost
POST http://localhost:8000/curatorships/posts
Content-Type: application/json

{
    "title": "Moses2",
    "body": "A guy who will become a king becomes a slave and than a king again"
}


### curator_id - johel : 3d2c8c50-282c-4dea-a911-c229384bdffa
### curator_id - gabriel: b221a17a-6c00-4f4b-bf46-2bb17687a53d
# @name newCuratorship
POST http://localhost:8000/curatorships/curatorships
Content-Type: application/json

{
    "category": "MOVIES",
    "curator_id": "3d2c8c50-282c-4dea-a911-c229384bdffa",
    "curr_status": "DRAFT",
    "exclusivity":"FREE",
    "frequency": "HOUR", 
    "previews_count": 1,
    "priority_order":"ASC",
    "verified": false,
    "single_price": 0.000123,
    "price_currency": "BTC",
    "metadata": {
        "hero_image": "https://via.placeholder.com/150/d32776",
        "title": "2022 - Melhores Filmes de terror",
        "subtitle": "Não pode perder",
        "text" : "Na minhao opiniao os 10 melhores filmes"
    },
    "items": [
        {
            "external_ref": "https://via.placeholder.com/150/d32776",
            "priority": 1,
            "metadata": {
                "hero_image": "https://via.placeholder.com/150/d32776",
                "title": "2022 - Melhores Filmes",
                "subtitle": "Não pode perder",
                "text" : "Na minhao opiniao os 10 melhores filmes"
            }
        }
    ]
}