###
# @name newPost
POST http://localhost:8000/curatorships/posts
Content-Type: application/json

{
    "title": "Moses2",
    "body": "A guy who will become a king becomes a slave and than a king again"
}


###
# @name newCuratorship
POST http://localhost:8000/curatorships/curatorships
Content-Type: application/json

{
    "category": "MOVIES",
    "curator_id": "e19de506-71eb-4abf-a6a3-1c080ad72727",
    "curr_status": "DRAFT",
    "exclusivity":"FREE",
    "frequency": "HOUR", 
    "previews_count": 1,
    "priority_order":"ASC",
    "verified": false,
    "metadata": {
        "hero_image": "https://via.placeholder.com/150/d32776",
        "title": "2022 - Melhores Filmes",
        "subtitle": "Não pode perder",
        "text" : "Na minhao opiniao os 10 melhores filmes"
    },
    "items": []
}